### ISSUE TITLE
DomainBlacklist (third and deep domen) with DomainWhitelist

### ISSUE THREAD

**Issue by iDolmatov** [CryShana/CryCrawler#1]
W: YYY.zz
B: ccn.YYY.zz
Download with blacklist domain.
![1](https://user-images.githubusercontent.com/19782385/63024042-d69aa200-bebf-11e9-8451-70f58a70eb41.png)

**Comment by iDolmatov** [comment]
P.s. At the current stage of the verification, it is not possible to load full-size images.
It looks like plugin processing is required. "Chukchi" is not a writer.

**Comment by CryShana** [comment]
It seems like the blacklist got skipped if the main domain was whitelisted.

I fixed this in the new release
https://github.com/CryShana/CryCrawler/releases/tag/v1.0.2
