### ISSUE TITLE
[request] URL download mask list

### ISSUE THREAD

**Issue by iDolmatov** [CryShana/CryCrawler#2]
Download URL mask.
Example whitelist:
*/original/*
Example blacklist:
domen.yy/profile/*

**Comment by CryShana** [comment]
Thank you for the request. This is pretty easy to implement, so I might add it either today or tomorrow.

**Comment by CryShana** [comment]
I have now implemented this - it is called `URL patterns`.

Every file URL is now compared to every URL pattern. At least one pattern must be matched to continue.

Check the following release:
https://github.com/CryShana/CryCrawler/releases/tag/v1.0.3

**Comment by CryShana** [comment]
The file URL pattern matching only applies to file URLs when downloading files.

I have now added a URL pattern **blacklist** that applies to all URLs.

https://github.com/CryShana/CryCrawler/releases/tag/v1.0.4
