### ISSUE TITLE
--version

### ISSUE THREAD

**Issue by iDolmatov** [CryShana/CryCrawler#4]
All version show CryCrawler 1.0.0.
Don't find version string on Source code (zip).

**Comment by CryShana** [comment]
Yeah, I know. I never specified the assembly/file version, that's why it's always 1.0.0.

That can be specified in the `.csproj` file by adding these two lines:
`<AssemblyVersion>1.0.3.0</AssemblyVersion>`
`<FileVersion>1.0.3.0</FileVersion>`

I will probably update it for the next release.
