### ISSUE TITLE
Say I want to crawl all images from a chan.sankakuchan tag, How would I use this program to download those images? I miss your api program

### ISSUE THREAD

**Issue by fluffyjin** [CryShana/CryCrawler#6]

**Comment by CryShana** [comment]
First of all, this is a general web crawler that will crawl through everything - it won't be as fast, efficient or reliable at finding Sankaku posts as the SankakuDownloader was.

However you could try using this for Sankaku by limiting crawling to their domain and only downloading images with certain extension, file size and URL pattern. (check the Simple configuration examples in the README file for the configuration)

I am still waiting for Sankaku developers to release an official API documentation and will most likely make a new Sankaku Downloader then.
